// src/common/layouts/vue/NavLayout.vue
<template>
  <div>
    <Alert type="error" v-if="!routes">{{LayoutStrings.Route_Loading_Failed}}</Alert>
    <Alert type="warning" v-else-if="!routes.length">{{LayoutStrings.Route_Empty}}</Alert>
    <template v-else>
      <li :v-for="route in routes" :key="route.path">{{route.name}}</li>
    </template>
  </div>
</template>

<script>
import { LayoutStrings } from '@/common/utils/LayoutStringUtil';
import cls from 'classnames';
import Alert from '@/common/components/error/fallbacks/Alert.vue';

export default {
  components: { Alert },
  props: {
    routes: {
      required: true
    }
    // with_react_router_dom,
    // className,
  },
  data() {
    return {
      LayoutStrings,
      
    }
  },
  setup() {
  }
}
</script>

// src/common/layouts/NavLayout.tsx
import React from 'react';

import { Link } from 'react-router-dom';

import cls from 'classnames';
import Alert from '../components/error/fallbacks/Alert';
import { LayoutStrings } from '../utils/LayoutStringUtil';

export interface Routes {
  name: string,
  path: string,
}

const NavLayout:React.FC<{
  routes: Routes[]
  with_react_router_dom?: boolean
  className?: any
}> = ({ routes, with_react_router_dom = false, className }) => {

  if (!routes) return <Alert type='error'>{LayoutStrings.Route_Loading_Failed}</Alert>
  else if (!routes.length) return <Alert type='warning'>{LayoutStrings.Route_Empty}</Alert>

  return (<div className={cls('router-list', className)}>
    {with_react_router_dom ?
      <ReactRouterDOMRoutes routes={routes}/> :
      <NaiveRoutes routes={routes}/>}
  </div>)
}

const go = (url) => {
  window.location.hash = `/${url}`
}

const NaiveRoutes:React.FC<{
  routes: Routes[],
}> = ({ routes }) => {
  return (<>
    {
      routes.map(({ name, path }, idx) => {
        return (
          <li onClick={() => go(path)} key={path}>{formatName(name)}</li>
        );
      })
    }
    </>);
}

const ReactRouterDOMRoutes:React.FC<{
  routes: Routes[]
}> = ({ routes }) => {
  return (<>
    {
      routes.map(({ name, path }, idx) => {
        return (
          <li key={`${idx}`}>
            <Link to={path}>
              {formatName(name)}
            </Link>
          </li>
        );
      })
    }
    </>);
}

const formatName = name => {
  return name.replace(/_/, ' ');
};

export default NavLayout;
